/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MultiTool;

/**
 *
 * @author Robert
 */
public class ConversieDistanta extends javax.swing.JFrame {

    /**
     * Creates new form ConvertInchCm
     */
    public ConversieDistanta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimetri", "Inch", "Feet", "Metri", "Mile", "Kilometri" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centimetri", "Inch", "Feet", "Metri", "Mile", "Kilometri" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Inapoi");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(94, 94, 94))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBox1, jComboBox2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBox2, jLabel3, jTextField1});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
    
    dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      jTextField1.setText("");
      jLabel3.setText("");
        
    }//GEN-LAST:event_jButton2ActionPerformed
   
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float Centimetri, Inch, Feet, Metri, Mile, Kilometri;
        //cm - cm
        if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 0 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Centimetri);
        }
        //cm-Inch
        else if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 1 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            Inch = (float)(Centimetri * 0.39370);
            jLabel3.setText(" " + Inch);
        }
        //cm-Feet
        else if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 2 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            Feet = (float)(Centimetri / 30.48);
            jLabel3.setText(" " + Feet);
        }
        //cm-Metri
        else if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 3 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            Metri = (float)(Centimetri / 100);
            jLabel3.setText(" " + Metri);
        }
        //cm-Mile
        else if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 4 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            Mile = (float)( Centimetri/160934.4);
            jLabel3.setText(" " + Mile);
        }
        //cm-Kilometri
        else if( jComboBox1.getSelectedIndex()== 0 && jComboBox2.getSelectedIndex()== 5 )  { 
            Centimetri = (float) Double.parseDouble(jTextField1.getText());
            Kilometri = (float)(Centimetri / 100000);
            jLabel3.setText(" " + Kilometri);
        }
        ////
        //INCH
        
        // Inch - cm
        if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 0 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            Centimetri = (float)(Inch * 2.54);
            jLabel3.setText(" " + Centimetri);
        }
        //Inch-Inch
        else if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 1 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Inch);
        }
        //Inch-Feet
        else if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 2 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            Feet = (float)(Inch * 0.083333);
            jLabel3.setText(" " + Feet);
        }
        //Inch-Metri
        else if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 3 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            Metri = (float)(Inch * 0.0254);
            jLabel3.setText(" " + Metri);
        }
        //Inch-Mile
        else if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 4 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            Mile = (float)(Inch / 63.360);
            jLabel3.setText(" " + Mile);
        }
        //Inch-Kilometri
        else if( jComboBox1.getSelectedIndex()== 1 && jComboBox2.getSelectedIndex()== 5 )  { 
            Inch = (float) Double.parseDouble(jTextField1.getText());
            Kilometri = (float)(Inch / 39370);
            jLabel3.setText(" " + Kilometri);
        }
        ////
        
        //FEET
        
        // feet - cm
        if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 0 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            Centimetri = (float)(Feet * 30.48 );
            jLabel3.setText(" " + Centimetri);
        }
        //feet-Inch
        else if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 1 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            Inch = Feet * 12;
            jLabel3.setText(" " + Inch);
        }
        //feet-feet
        else if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 2 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Feet);
        }
        //feet-Metri
        else if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 3 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            Metri = (float)(Feet *  0.3048);
            jLabel3.setText(" " + Metri);
        }
        //feet-Mile
        else if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 4 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            Mile = (float)(Feet *  0.00018939);
            jLabel3.setText(" " + Mile);
        }
        //feet-Kilometri
        else if( jComboBox1.getSelectedIndex()== 2 && jComboBox2.getSelectedIndex()== 5 )  { 
            Feet = (float) Double.parseDouble(jTextField1.getText());
            Kilometri = (float)(Feet / 3280.8);
            jLabel3.setText(" " + Kilometri);
        }
        ////
  
        
        //Metri
        
        // Metri - cm
        if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 0 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            Centimetri = (float)(Metri / 0.010000    );
            jLabel3.setText(" " + Centimetri);
        }
        //Metri-Inch
        else if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 1 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            Inch = (float)(Metri / 0.0254);
            jLabel3.setText(" " + Inch);
        }
        //Metri-feet
        else if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 2 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            Feet = (float)(Metri / 0.3048);
            jLabel3.setText(" " + Feet);
        }
        //Metri-Metri
        else if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 3 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Metri);
        }
        //Metri-Mile
        else if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 4 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            Mile = (float)(Metri * 0.00062137);
            jLabel3.setText(" " + Mile);
        }
        //Metri-Kilometri
        else if( jComboBox1.getSelectedIndex()== 3 && jComboBox2.getSelectedIndex()== 5 )  { 
            Metri = (float) Double.parseDouble(jTextField1.getText());
            Kilometri = (float)(Metri / 1000.0);
            jLabel3.setText(" " + Kilometri);
        }
        ////
        
        
        //Mile
        
        // Mile - cm
        if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 0 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            Centimetri = (float)(Mile * 160934.4);
            jLabel3.setText(" " + Centimetri);
        }
        //Mile-Inch
        else if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 1 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            Inch = (float)(Mile * 63360);
            jLabel3.setText(" " + Inch);
        }
        //Mile-feet
        else if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 2 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            Feet = (float)(Mile * 5280.0);
            jLabel3.setText(" " + Feet);
        }
        //Mile-Metri
        else if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 3 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Mile);
        }
        //Mile-Mile
        else if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 4 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Mile);
        }
        //Mile-Kilometri
        else if( jComboBox1.getSelectedIndex()== 4 && jComboBox2.getSelectedIndex()== 5 )  { 
            Mile = (float) Double.parseDouble(jTextField1.getText());
            Kilometri = (float)(Mile / 0.62137);
            jLabel3.setText(" " + Kilometri);
        }
        ////
        
        //Kilometri
        
        //Kilometri - cm
        if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 0 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            Centimetri = (float)(Kilometri * 100000);
            jLabel3.setText(" " + Centimetri);
        }
        //Kilometri-Inch
        else if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 1 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            Inch = (float)(Kilometri * 39370);
            jLabel3.setText(" " + Inch);
        }
        //Kilometri-feet
        else if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 2 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            Feet = (float)(Kilometri * 3280.8);
            jLabel3.setText(" " + Feet);
        }
        //Kilometri-Metri
        else if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 3 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            Metri = (float)(Kilometri / 0.0010000); 
            jLabel3.setText(" " + Metri);
        }
        //Kilometri-Mile
        else if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 4 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            Mile = (float)(Kilometri * 0.62137);
            jLabel3.setText(" " + Mile);
        }
        //Kilometri-Kilometri
        else if( jComboBox1.getSelectedIndex()== 5 && jComboBox2.getSelectedIndex()== 5 )  { 
            Kilometri = (float) Double.parseDouble(jTextField1.getText());
            jLabel3.setText(" " + Kilometri);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
 
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversieDistanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversieDistanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversieDistanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversieDistanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversieDistanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
